version: '3'
services:
  db:
    image: postgres:10.12-alpine
    container_name: postgres
    ports:
      - 5433:5432
    volumes: 
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: imagesDB
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    build: .
    container_name: application
    expose:
      - 8080
    ports:
      - 8088:8080
    volumes:
      - ./uploadImages:/uploadImages
    depends_on:
      - db
    links:
      - db